# Generated by Django 5.2.4 on 2025-07-30 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('student_registrations', 'Student Registrations'), ('maintenance_requests', 'Maintenance Requests'), ('tickets', 'Tickets'), ('ticket_messages', 'Ticket Messages'), ('maintenance_status_changes', 'Maintenance Status Changes')], max_length=30)),
                ('last_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['admin_user', 'activity_type'], name='notificatio_admin_u_43b6ab_idx')],
                'unique_together': {('admin_user', 'activity_type')},
            },
        ),
    ]
