# Generated by Django 5.2.4 on 2025-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitytracker',
            name='activity_type',
            field=models.CharField(choices=[('student_registrations', 'Student Registrations'), ('maintenance_requests', 'Maintenance Requests'), ('maintenance_status_changes', 'Maintenance Status Changes'), ('maintenance_completed', 'Maintenance Completed'), ('tickets', 'Tickets'), ('ticket_messages', 'Ticket Messages')], max_length=30),
        ),
    ]
