# Generated by Django 5.2.4 on 2025-08-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_adminactivitytracker_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitytracker',
            name='activity_type',
            field=models.CharField(choices=[('student_registrations', 'Student Registrations'), ('maintenance_requests', 'Maintenance Requests'), ('tickets', 'Tickets'), ('ticket_messages', 'Ticket Messages')], max_length=30),
        ),
    ]
