# Generated by Django 5.2.4 on 2025-07-10 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC/Air Conditioning'), ('carpentry', 'Carpentry'), ('general', 'General Maintenance'), ('cleaning', 'Cleaning'), ('security', 'Security Systems')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Expert',
                'verbose_name_plural': 'Service Experts',
            },
        ),
    ]
