# Generated by Django 5.2.4 on 2025-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexpert',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from completed requests', max_digits=3, null=True),
        ),
    ]
