# Generated by Django 5.2.4 on 2025-10-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_serviceexpert_average_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceexpert',
            options={'verbose_name': 'متخصص خدمات', 'verbose_name_plural': 'متخصصان خدمات'},
        ),
    ]
