# Generated by Django 5.2.4 on 2025-10-01 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_serviceexpert_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceexpert',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='میانگین امتیاز از درخواست\u200cهای تکمیل شده', max_digits=3, null=True, verbose_name='میانگین امتیاز'),
        ),
        migrations.AlterField(
            model_name='serviceexpert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='serviceexpert',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='شماره کارمندی'),
        ),
        migrations.AlterField(
            model_name='serviceexpert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='serviceexpert',
            name='specialization',
            field=models.CharField(choices=[('electrical', 'برق'), ('plumbing', 'لوله\u200cکشی'), ('hvac', 'تهویه مطبوع'), ('carpentry', 'نجاری'), ('general', 'تعمیرات عمومی'), ('cleaning', 'نظافت'), ('security', 'سیستم\u200cهای امنیتی')], max_length=20, verbose_name='تخصص'),
        ),
        migrations.AlterField(
            model_name='serviceexpert',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
