# Generated by Django 5.2.4 on 2025-07-10 13:13

import django.core.validators
import django.db.models.deletion
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('student', '0002_remove_student_processed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service_type', models.CharField(choices=[('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC/Air Conditioning'), ('carpentry', 'Carpentry'), ('general', 'General Maintenance'), ('cleaning', 'Cleaning'), ('security', 'Security Systems')], help_text='Type of service required', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('issue_image', models.ImageField(blank=True, null=True, upload_to='maintenance_issues/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('approved_by_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('work_started_at', models.DateTimeField(blank=True, null=True)),
                ('expert_notes', models.TextField(blank=True)),
                ('completion_image', models.ImageField(blank=True, null=True, upload_to='maintenance_completed/')),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student_rating', models.IntegerField(blank=True, help_text='Rating from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('student_feedback', models.TextField(blank=True)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='service.serviceexpert')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='student.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=maintenance.models.MaintenanceImage.get_upload_path)),
                ('image_type', models.CharField(choices=[('issue', 'Issue Image'), ('completion', 'Completion Image')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.maintenancerequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
