# Generated by Django 5.2 on 2025-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('not_decided', 'Not Decided'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='not_decided', max_length=20),
        ),
    ]
