# Generated by Django 5.2.4 on 2025-07-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancerequest_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='completion_image',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='issue_image',
        ),
    ]
