# Generated by Django 5.2.4 on 2025-10-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancerequest_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceimage',
            options={'verbose_name': 'تصویر تعمیرات', 'verbose_name_plural': 'تصاویر تعمیرات'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست تعمیرات', 'verbose_name_plural': 'درخواست\u200cهای تعمیرات'},
        ),
    ]
