# Generated by Django 5.2.4 on 2025-10-01 20:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenanceimage_options_and_more'),
        ('service', '0004_alter_serviceexpert_average_rating_and_more'),
        ('student', '0007_alter_building_created_at_alter_building_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceimage',
            name='image',
            field=models.ImageField(upload_to=maintenance.models.MaintenanceImage.get_upload_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='maintenanceimage',
            name='image_type',
            field=models.CharField(choices=[('issue', 'تصویر مشکل'), ('completion', 'تصویر تکمیل')], max_length=10, verbose_name='نوع تصویر'),
        ),
        migrations.AlterField(
            model_name='maintenanceimage',
            name='maintenance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maintenance.maintenancerequest', verbose_name='درخواست تعمیرات'),
        ),
        migrations.AlterField(
            model_name='maintenanceimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='approved_by_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تایید شده توسط'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تخصیص'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='service.serviceexpert', verbose_name='متخصص تخصیص داده شده'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='completion_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای تکمیل'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='expert_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای متخصص'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نظر'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='priority',
            field=models.CharField(choices=[('not_decided', 'تعیین نشده'), ('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='not_decided', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='دلیل رد'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='student.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='service_type',
            field=models.CharField(choices=[('electrical', 'برق'), ('plumbing', 'لوله\u200cکشی'), ('hvac', 'تهویه مطبوع'), ('carpentry', 'نجاری'), ('general', 'تعمیرات عمومی'), ('cleaning', 'نظافت'), ('security', 'سیستم\u200cهای امنیتی')], help_text='نوع خدمات مورد نیاز', max_length=20, verbose_name='نوع سرویس'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=15, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='student.student', verbose_name='دانشجو'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='student_feedback',
            field=models.TextField(blank=True, verbose_name='نظر دانشجو'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='student_rating',
            field=models.IntegerField(blank=True, help_text='امتیاز از ۱ تا ۵', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز دانشجو'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع کار'),
        ),
    ]
