# Generated by Django 5.2.4 on 2025-07-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='processed_by',
        ),
        migrations.AddField(
            model_name='student',
            name='processed_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('expert', 'Service Expert')], max_length=10, null=True),
        ),
    ]
