# Generated by Django 5.2 on 2025-07-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_room_is_occupied_student_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(unique=True),
        ),
    ]
