# Generated by Django 5.2.4 on 2025-10-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_student_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'ساختمان', 'verbose_name_plural': 'ساختمان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'floor', 'number'], 'verbose_name': 'اتاق', 'verbose_name_plural': 'اتاق\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'دانشجو', 'verbose_name_plural': 'دانشجویان'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
