# Generated by Django 5.2.4 on 2025-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_building_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'دانشجو'), ('expert', 'متخصص خدمات')], max_length=10, null=True),
        ),
    ]
