# Generated by Django 5.2.4 on 2025-10-01 20:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floors',
            field=models.IntegerField(verbose_name='تعداد طبقات'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='student.building', verbose_name='ساختمان'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=6, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(verbose_name='طبقه'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش'),
        ),
        migrations.AlterField(
            model_name='student',
            name='processed_by_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='پردازش شده توسط'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت ثبت\u200cنام'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='دلیل رد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.IntegerField(unique=True, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='توکن تایید'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='کارمند'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'دانشجو'), ('expert', 'متخصص خدمات')], max_length=10, null=True, verbose_name='نوع کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام کاربری'),
        ),
    ]
