# Generated by Django 5.2.4 on 2025-07-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attachment', null=True, upload_to='ticket_images/%Y/%m/%d/'),
        ),
    ]
