# Generated by Django 5.2.4 on 2025-07-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='read_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
