# Generated by Django 5.2.4 on 2025-10-01 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketmessage_read_by_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'پیام تیکت', 'verbose_name_plural': 'پیام\u200cهای تیکت'},
        ),
    ]
